version: "3.8"
services: 
  web: 
    image: shokhboz11/todo-do-server:latest
    depends_on: 
      - db
    ports: 
      - "3000:3000"
    environment: 
     POSTGRES_HOST: db
    env_file: .env
    
  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data